### PR TITLE
2017 03

### PR DESCRIPTION
**Pull request by shunjikonishi**
- Add test directory
  - java - Source file with Japanese string
  - C++ - `std::to_string`
- Update Dockerfile
  - Specify phpunit version. (Now `phpunit` without version means php7 version.)
- Update codecheck CLI to 0.6.2
- Update python3 to 3.6.1
- Add language-pack-en and specify `LANG=en_US.UTF-8`
- Add rust

@takayukioda review me

### CODE REVIEW

**Comment by takayukioda** [comment]
I'm not sure why circle ci is failing, but codes seems good
https://media.giphy.com/media/l2YWfJqwZSSFEbCg0/giphy.gif

**Comment by takayukioda** [comment]
I'm not sure why circle ci is failing, but codes seems good
LGTM

**Comment by shunjikonishi** [comment]
@takayukioda 
I've changed some test. Now CI running again.

Because the behavior of test.sh is bit different in CircleCI.

test.sh has some rows like this.

```
[[ "`docker run --rm all cabal info hspec`" == *'Versions installed: 2.4.3'* ]]
```

On local env, these rows are just ignored even if this condition is not correct. and continue to next step.
But on CircleCI stops if this condition is not correct.

I don't know why.

**Comment by shunjikonishi** [comment]
CI passed

**Pull request merged**
