### PR TITLE
feat: remove karma and add nightmare and dependencies

### PR DESCRIPTION
**Pull request by TsubasaK111**
- Removes karma.
  - Karma is another headless browser end to end integration test framework.
  - Karma is currently not used by any challenge or unit test.
  - Karma is not very performant. I personally do not recommend using it for any codecheck / codeprep content.

- Adds nightmarejs and it's dependencies
  - nightmarejs is currently used in at least 2 challenges.  
     By installing this heavy framework, we can Improve user experience.
  - nightmarejs is the most reasonably performant e2e web browser integration test framework that I know of.
  - As we have proven that this works in challenges, I am comfortable using this tool for codecheck content.

### CODE REVIEW

**Comment by TsubasaK111** [comment]
@shunjikonishi @takayukioda review me!

**Comment by TsubasaK111** [comment]
JBS will start using a challenge with nightmarejs starting from next next week. I understand that this will require some careful testing, but it would be ideal if we can have this deployed by 10/22.

**Comment by bschwind** [comment]
This seems good, but do you think you could add a testing line to `test.sh` to prove that nightmarejs is working correctly?

**Comment by takayukioda** [comment]
build is succeeded, but I've got following warning. Would you fix to avoid this warning?
it seems your comment about dirty hack (or empty lines near that) is the cause of this warning

```
[WARNING]: Empty continuation line found in:
    RUN apt-add-repository -y ppa:webupd8team/java &&   apt-get update -qq &&   echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections &&   (apt-get install -qqy oracle-java8-installer ca-certificates oracle-java8-set-default maven ||    sed -i 's|JAVA_VERSION=8u144|JAVA_VERSION=8u152|' /var/lib/dpkg/info/oracle-java8-installer.* &&    sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/|' /var/lib/dpkg/info/oracle-java8-installer.* &&    sed -i 's|SHA256SUM_TGZ="e8a341ce566f32c3d06f6d0f0eeea9a0f434f538d22af949ae58bc86f2eeaae4"|SHA256SUM_TGZ="218b3b340c3f6d05d940b817d0270dfe0cfd657a636bad074dcabe0c111961bf"|' /var/lib/dpkg/info/oracle-java8-installer.* &&    sed -i 's|J_DIR=jdk1.8.0_144|J_DIR=jdk1.8.0_152|' /var/lib/dpkg/info/oracle-java8-installer.*) &&   apt-get install -qqy oracle-java8-installer ca-certificates oracle-java8-set-default maven &&   rm -rf /var/lib/apt/lists/*
[WARNING]: Empty continuation lines will become errors in a future release.
```

**Review by takayukioda — CHANGES_REQUESTED** [review]
Please fix warning, and give us idea for testing in `test.sh` as bschwind mentioned

**Review by takayukioda — APPROVED** [review]

**Review by shunjikonishi — APPROVED** [review]
test.sh works

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
