### PR TITLE
Remove ansible

### PR DESCRIPTION
**Pull request by shokohara**
@takayukioda review me

### CODE REVIEW

**Comment by shokohara** [comment]
https://github.com/code-check/env-builder/issues/54

**Comment by shokohara** [comment]
`docker run givery/codecheck:latest codecheck versions` and `docker run givery/codecheck:test codecheck versions` diff is below

```
< PHP 5.6.21-1+donate.sury.org~trusty+4 (cli)
---
> PHP 5.6.21-7+donate.sury.org~trusty+1 (cli)
```

**Comment by takayukioda** [comment]
Would you write the section by comment in Dockerfile?

Dockerfileをセクションごとでコメント挟んでおいてもらえますか？

LGTM

**Comment by shokohara** [comment]
@takayukioda I wrote comment. Thanks for reviewing.

**Pull request merged**
